import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const additionalProducts = [
  {
    slug: "dining-set-oak-6-chairs",
    nameEn: "Oak Dining Set with 6 Chairs",
    nameVi: "Bộ Bàn Ăn Gỗ Sồi với 6 Ghế",
    descriptionEn: "Complete dining set with oak table and 6 matching chairs",
    descriptionVi: "Bộ bàn ăn hoàn chỉnh với bàn gỗ sồi và 6 ghế phù hợp",
    price: 1299.99,
    originalPrice: 1599.99,
    images: ["/images/business-slide3.jpg", "/images/business-slide5.jpg"],
    room: "Dining Room",
    type: "Table",
    combo: "Dining Set",
    category: "Furniture",
    inStock: true,
    stock: 5,
    featured: true,
    featuresEn: ["Solid oak", "6 chairs included", "Natural finish"],
    featuresVi: ["Gỗ sồi nguyên khối", "Bao gồm 6 ghế", "Hoàn thiện tự nhiên"],
    longDescriptionEn: "Complete dining room solution with beautiful oak table and 6 matching chairs. Perfect for family dinners and entertaining guests.",
    longDescriptionVi: "Giải pháp phòng ăn hoàn chỉnh với bàn gỗ sồi đẹp và 6 ghế phù hợp. Hoàn hảo cho bữa tối gia đình và tiếp khách.",
    specificationsEn: { "Table Size": "180x90cm", "Chair Height": "90cm", "Material": "Solid Oak" },
    specificationsVi: { "Kích thước bàn": "180x90cm", "Chiều cao ghế": "90cm", "Chất liệu": "Gỗ Sồi Nguyên Khối" }
  },
  {
    slug: "leather-recliner-chair",
    nameEn: "Leather Recliner Chair",
    nameVi: "Ghế Thư Giãn Bằng Da",
    descriptionEn: "Comfortable leather recliner chair for relaxation",
    descriptionVi: "Ghế thư giãn bằng da thoải mái để nghỉ ngơi",
    price: 899.99,
    originalPrice: 1199.99,
    images: ["/images/business-slide1.jpg", "/images/business-slide2.jpg"],
    room: "Living Room",
    type: "Chair",
    category: "Furniture",
    inStock: true,
    stock: 8,
    featured: false,
    featuresEn: ["Genuine leather", "Reclining function", "Cup holder"],
    featuresVi: ["Da thật", "Chức năng ngả", "Chỗ để cốc"],
    longDescriptionEn: "Luxurious leather recliner chair with multiple reclining positions and built-in cup holder for ultimate comfort.",
    longDescriptionVi: "Ghế thư giãn da sang trọng với nhiều vị trí ngả và chỗ để cốc tích hợp để thoải mái tối đa.",
    specificationsEn: { "Width": "85cm", "Depth": "95cm", "Height": "105cm", "Material": "Genuine Leather" },
    specificationsVi: { "Chiều rộng": "85cm", "Chiều sâu": "95cm", "Chiều cao": "105cm", "Chất liệu": "Da Thật" }
  },
  {
    slug: "wardrobe-sliding-doors",
    nameEn: "3-Door Sliding Wardrobe",
    nameVi: "Tủ Quần Áo 3 Cánh Trượt",
    descriptionEn: "Spacious wardrobe with sliding doors and mirrors",
    descriptionVi: "Tủ quần áo rộng rãi với cửa trượt và gương",
    price: 1199.99,
    images: ["/images/business-slide6.jpg", "/images/business-slide1.jpg"],
    room: "Bedroom",
    type: "Cabinet",
    category: "Storage",
    inStock: true,
    stock: 6,
    featured: true,
    featuresEn: ["3 sliding doors", "Mirrored panels", "Multiple compartments"],
    featuresVi: ["3 cửa trượt", "Tấm gương", "Nhiều ngăn"],
    longDescriptionEn: "Large wardrobe with sliding doors and mirrored panels, offering ample storage space for clothes and accessories.",
    longDescriptionVi: "Tủ quần áo lớn với cửa trượt và tấm gương, cung cấp không gian lưu trữ rộng cho quần áo và phụ kiện.",
    specificationsEn: { "Width": "250cm", "Depth": "60cm", "Height": "220cm", "Material": "MDF + Mirror" },
    specificationsVi: { "Chiều rộng": "250cm", "Chiều sâu": "60cm", "Chiều cao": "220cm", "Chất liệu": "MDF + Gương" }
  },
  {
    slug: "executive-office-desk",
    nameEn: "Executive Office Desk",
    nameVi: "Bàn Làm Việc Giám Đốc",
    descriptionEn: "Large executive desk with built-in drawers",
    descriptionVi: "Bàn giám đốc lớn với ngăn kéo tích hợp",
    price: 799.99,
    originalPrice: 999.99,
    images: ["/images/business-slide2.jpg", "/images/business-slide3.jpg"],
    room: "Office",
    type: "Desk",
    category: "Furniture",
    inStock: true,
    stock: 10,
    featured: false,
    featuresEn: ["Large surface", "Built-in drawers", "Cable management"],
    featuresVi: ["Bề mặt lớn", "Ngăn kéo tích hợp", "Quản lý dây cáp"],
    longDescriptionEn: "Professional executive desk with spacious work surface, built-in storage drawers, and integrated cable management system.",
    longDescriptionVi: "Bàn giám đốc chuyên nghiệp với bề mặt làm việc rộng rãi, ngăn kéo lưu trữ tích hợp và hệ thống quản lý dây cáp tích hợp.",
    specificationsEn: { "Length": "160cm", "Width": "80cm", "Height": "75cm", "Material": "Wood Veneer" },
    specificationsVi: { "Chiều dài": "160cm", "Chiều rộng": "80cm", "Chiều cao": "75cm", "Chất liệu": "Veneer Gỗ" }
  },
  {
    slug: "sectional-sofa-l-shape",
    nameEn: "L-Shape Sectional Sofa",
    nameVi: "Sofa Góc Hình L",
    descriptionEn: "Large L-shaped sectional sofa for corner placement",
    descriptionVi: "Sofa góc hình L lớn để đặt góc",
    price: 1599.99,
    originalPrice: 1999.99,
    images: ["/images/business-slide1.jpg", "/images/business-slide5.jpg"],
    room: "Living Room",
    type: "Sofa",
    category: "Furniture",
    inStock: true,
    stock: 4,
    featured: true,
    featuresEn: ["L-shaped design", "7-seater", "Premium fabric"],
    featuresVi: ["Thiết kế hình L", "7 chỗ ngồi", "Vải cao cấp"],
    longDescriptionEn: "Spacious L-shaped sectional sofa that can accommodate up to 7 people, perfect for large living rooms and entertaining.",
    longDescriptionVi: "Sofa góc hình L rộng rãi có thể chứa tới 7 người, hoàn hảo cho phòng khách lớn và tiếp khách.",
    specificationsEn: { "Length": "280cm", "Width": "200cm", "Height": "85cm", "Material": "Fabric + Foam" },
    specificationsVi: { "Chiều dài": "280cm", "Chiều rộng": "200cm", "Chiều cao": "85cm", "Chất liệu": "Vải + Xốp" }
  },
  {
    slug: "kitchen-island-marble",
    nameEn: "Marble Top Kitchen Island",
    nameVi: "Đảo Bếp Mặt Đá Cẩm Thạch",
    descriptionEn: "Kitchen island with marble top and storage",
    descriptionVi: "Đảo bếp với mặt đá cẩm thạch và chỗ lưu trữ",
    price: 2199.99,
    images: ["/images/business-slide3.jpg", "/images/business-slide6.jpg"],
    room: "Kitchen",
    type: "Cabinet",
    category: "Furniture",
    inStock: true,
    stock: 3,
    featured: true,
    featuresEn: ["Marble countertop", "Storage cabinets", "Breakfast bar"],
    featuresVi: ["Mặt bàn đá cẩm thạch", "Tủ lưu trữ", "Quầy ăn sáng"],
    longDescriptionEn: "Elegant kitchen island featuring a beautiful marble countertop, ample storage space, and breakfast bar seating.",
    longDescriptionVi: "Đảo bếp thanh lịch có mặt bàn đá cẩm thạch đẹp, không gian lưu trữ rộng và chỗ ngồi quầy ăn sáng.",
    specificationsEn: { "Length": "200cm", "Width": "90cm", "Height": "90cm", "Material": "Marble + Wood" },
    specificationsVi: { "Chiều dài": "200cm", "Chiều rộng": "90cm", "Chiều cao": "90cm", "Chất liệu": "Cẩm Thạch + Gỗ" }
  },
  {
    slug: "study-desk-kids",
    nameEn: "Kids Study Desk with Hutch",
    nameVi: "Bàn Học Trẻ Em Có Kệ",
    descriptionEn: "Child-friendly study desk with overhead storage",
    descriptionVi: "Bàn học thân thiện với trẻ em có kệ lưu trữ phía trên",
    price: 399.99,
    originalPrice: 499.99,
    images: ["/images/business-slide2.jpg", "/images/business-slide5.jpg"],
    room: "Bedroom",
    type: "Desk",
    category: "Furniture",
    inStock: true,
    stock: 15,
    featured: false,
    featuresEn: ["Child-safe design", "Storage hutch", "Adjustable shelf"],
    featuresVi: ["Thiết kế an toàn cho trẻ", "Kệ lưu trữ", "Kệ điều chỉnh"],
    longDescriptionEn: "Perfect study desk for children with child-safe design, overhead storage hutch, and adjustable shelving for books and supplies.",
    longDescriptionVi: "Bàn học hoàn hảo cho trẻ em với thiết kế an toàn cho trẻ, kệ lưu trữ phía trên và kệ điều chỉnh cho sách và đồ dùng.",
    specificationsEn: { "Width": "120cm", "Depth": "60cm", "Height": "140cm", "Material": "MDF + Pine" },
    specificationsVi: { "Chiều rộng": "120cm", "Chiều sâu": "60cm", "Chiều cao": "140cm", "Chất liệu": "MDF + Thông" }
  },
  {
    slug: "outdoor-patio-set",
    nameEn: "4-Piece Outdoor Patio Set",
    nameVi: "Bộ Nội Thất Sân Vườn 4 Món",
    descriptionEn: "Weather-resistant outdoor furniture set",
    descriptionVi: "Bộ nội thất ngoài trời chống thời tiết",
    price: 899.99,
    originalPrice: 1199.99,
    images: ["/images/business-slide1.jpg", "/images/business-slide3.jpg"],
    room: "Outdoor",
    type: "Table",
    combo: "Outdoor Set",
    category: "Outdoor",
    inStock: true,
    stock: 7,
    featured: false,
    featuresEn: ["Weather-resistant", "4 pieces", "Easy maintenance"],
    featuresVi: ["Chống thời tiết", "4 món", "Bảo trì dễ dàng"],
    longDescriptionEn: "Complete outdoor furniture set including table and chairs, designed to withstand weather elements while maintaining style and comfort.",
    longDescriptionVi: "Bộ nội thất ngoài trời hoàn chỉnh bao gồm bàn và ghế, được thiết kế để chịu được các yếu tố thời tiết trong khi vẫn duy trì phong cách và sự thoải mái.",
    specificationsEn: { "Table": "120x80cm", "Chairs": "4 included", "Material": "Aluminum + Textilene" },
    specificationsVi: { "Bàn": "120x80cm", "Ghế": "4 cái", "Chất liệu": "Nhôm + Textilene" }
  },
  {
    slug: "bedroom-set-complete",
    nameEn: "Complete Bedroom Set",
    nameVi: "Bộ Phòng Ngủ Hoàn Chỉnh",
    descriptionEn: "5-piece bedroom set with bed, nightstands, and dresser",
    descriptionVi: "Bộ phòng ngủ 5 món với giường, tủ đầu giường và tủ ngăn kéo",
    price: 2499.99,
    originalPrice: 2999.99,
    images: ["/images/business-slide6.jpg", "/images/business-slide2.jpg"],
    room: "Bedroom",
    type: "Bed",
    combo: "Bedroom Combo",
    category: "Furniture",
    inStock: true,
    stock: 2,
    featured: true,
    featuresEn: ["5-piece set", "Matching design", "Ample storage"],
    featuresVi: ["Bộ 5 món", "Thiết kế phù hợp", "Lưu trữ rộng"],
    longDescriptionEn: "Complete bedroom furniture set including king bed, two nightstands, dresser, and mirror. All pieces feature matching design and quality construction.",
    longDescriptionVi: "Bộ nội thất phòng ngủ hoàn chỉnh bao gồm giường king, hai tủ đầu giường, tủ ngăn kéo và gương. Tất cả các món đều có thiết kế phù hợp và chất lượng xây dựng.",
    specificationsEn: { "Bed Size": "King", "Nightstands": "2 included", "Material": "Solid Wood" },
    specificationsVi: { "Kích thước giường": "King", "Tủ đầu giường": "2 cái", "Chất liệu": "Gỗ Nguyên Khối" }
  },
  {
    slug: "bar-stool-set-4",
    nameEn: "Set of 4 Bar Stools",
    nameVi: "Bộ 4 Ghế Bar",
    descriptionEn: "Modern bar stools with adjustable height",
    descriptionVi: "Ghế bar hiện đại với độ cao điều chỉnh",
    price: 299.99,
    originalPrice: 399.99,
    images: ["/images/business-slide4.jpg", "/images/business-slide5.jpg"],
    room: "Kitchen",
    type: "Chair",
    category: "Furniture",
    inStock: true,
    stock: 12,
    featured: false,
    featuresEn: ["Set of 4", "Adjustable height", "Swivel function"],
    featuresVi: ["Bộ 4 ghế", "Độ cao điều chỉnh", "Xoay 360 độ"],
    longDescriptionEn: "Set of 4 modern bar stools with adjustable height and swivel function, perfect for kitchen islands and home bars.",
    longDescriptionVi: "Bộ 4 ghế bar hiện đại với độ cao điều chỉnh và chức năng xoay, hoàn hảo cho đảo bếp và quầy bar gia đình.",
    specificationsEn: { "Height": "60-80cm adjustable", "Seat Width": "35cm", "Material": "Metal + PU Leather" },
    specificationsVi: { "Chiều cao": "60-80cm điều chỉnh", "Chiều rộng ghế": "35cm", "Chất liệu": "Kim loại + Da PU" }
  },
  {
    slug: "tv-entertainment-center",
    nameEn: "TV Entertainment Center",
    nameVi: "Kệ TV Giải Trí",
    descriptionEn: "Large entertainment center for TVs up to 75 inches",
    descriptionVi: "Kệ giải trí lớn cho TV tới 75 inch",
    price: 699.99,
    originalPrice: 899.99,
    images: ["/images/business-slide1.jpg", "/images/business-slide6.jpg"],
    room: "Living Room",
    type: "Cabinet",
    category: "Storage",
    inStock: true,
    stock: 9,
    featured: false,
    featuresEn: ["Fits TVs up to 75\"", "Cable management", "Multiple shelves"],
    featuresVi: ["Phù hợp TV tới 75\"", "Quản lý dây cáp", "Nhiều kệ"],
    longDescriptionEn: "Spacious entertainment center that accommodates large TVs up to 75 inches with ample storage for media equipment and accessories.",
    longDescriptionVi: "Kệ giải trí rộng rãi có thể chứa TV lớn tới 75 inch với chỗ lưu trữ rộng cho thiết bị media và phụ kiện.",
    specificationsEn: { "Width": "200cm", "Depth": "45cm", "Height": "60cm", "Material": "Engineered Wood" },
    specificationsVi: { "Chiều rộng": "200cm", "Chiều sâu": "45cm", "Chiều cao": "60cm", "Chất liệu": "Gỗ Công Nghiệp" }
  },
  {
    slug: "office-chair-mesh-back",
    nameEn: "High-Back Mesh Office Chair",
    nameVi: "Ghế Văn Phòng Lưng Cao Lưới",
    descriptionEn: "Professional mesh back office chair with armrests",
    descriptionVi: "Ghế văn phòng lưng lưới chuyên nghiệp có tay vịn",
    price: 449.99,
    originalPrice: 599.99,
    images: ["/images/business-slide2.jpg", "/images/business-slide3.jpg"],
    room: "Office",
    type: "Chair",
    category: "Furniture",
    inStock: true,
    stock: 18,
    featured: false,
    featuresEn: ["High back support", "Mesh design", "Adjustable armrests"],
    featuresVi: ["Hỗ trợ lưng cao", "Thiết kế lưới", "Tay vịn điều chỉnh"],
    longDescriptionEn: "Professional high-back office chair with breathable mesh design, adjustable armrests, and excellent lumbar support for all-day comfort.",
    longDescriptionVi: "Ghế văn phòng lưng cao chuyên nghiệp với thiết kế lưới thoáng khí, tay vịn điều chỉnh và hỗ trợ thắt lưng tuyệt vời cho sự thoải mái cả ngày.",
    specificationsEn: { "Height": "110-120cm", "Seat Width": "50cm", "Material": "Mesh + Fabric" },
    specificationsVi: { "Chiều cao": "110-120cm", "Chiều rộng ghế": "50cm", "Chất liệu": "Lưới + Vải" }
  },
  {
    slug: "round-dining-table-4-seater",
    nameEn: "Round Dining Table for 4",
    nameVi: "Bàn Ăn Tròn 4 Chỗ",
    descriptionEn: "Compact round dining table perfect for small spaces",
    descriptionVi: "Bàn ăn tròn nhỏ gọn hoàn hảo cho không gian nhỏ",
    price: 449.99,
    originalPrice: 599.99,
    images: ["/images/business-slide3.jpg", "/images/business-slide5.jpg"],
    room: "Dining Room",
    type: "Table",
    category: "Furniture",
    inStock: true,
    stock: 11,
    featured: false,
    featuresEn: ["Round design", "4-seater", "Space-saving"],
    featuresVi: ["Thiết kế tròn", "4 chỗ ngồi", "Tiết kiệm không gian"],
    longDescriptionEn: "Elegant round dining table designed for 4 people, perfect for apartments and smaller dining areas while maintaining style and functionality.",
    longDescriptionVi: "Bàn ăn tròn thanh lịch được thiết kế cho 4 người, hoàn hảo cho căn hộ và khu vực ăn uống nhỏ hơn trong khi vẫn duy trì phong cách và chức năng.",
    specificationsEn: { "Diameter": "120cm", "Height": "75cm", "Material": "MDF + Wood Veneer" },
    specificationsVi: { "Đường kính": "120cm", "Chiều cao": "75cm", "Chất liệu": "MDF + Veneer Gỗ" }
  },
  {
    slug: "accent-chair-velvet",
    nameEn: "Velvet Accent Chair",
    nameVi: "Ghế Nhấn Nhung",
    descriptionEn: "Luxurious velvet accent chair in emerald green",
    descriptionVi: "Ghế nhấn nhung sang trọng màu xanh lục bảo",
    price: 599.99,
    originalPrice: 799.99,
    images: ["/images/business-slide1.jpg", "/images/business-slide2.jpg"],
    room: "Living Room",
    type: "Chair",
    category: "Furniture",
    inStock: true,
    stock: 6,
    featured: true,
    featuresEn: ["Velvet upholstery", "Emerald green", "Gold legs"],
    featuresVi: ["Bọc nhung", "Màu xanh lục bảo", "Chân vàng"],
    longDescriptionEn: "Stunning accent chair upholstered in luxurious emerald green velvet with elegant gold-finished legs, perfect for adding a touch of glamour.",
    longDescriptionVi: "Ghế nhấn tuyệt đẹp được bọc bằng nhung xanh lục bảo sang trọng với chân mạ vàng thanh lịch, hoàn hảo để thêm nét quyến rũ.",
    specificationsEn: { "Width": "70cm", "Depth": "75cm", "Height": "85cm", "Material": "Velvet + Metal" },
    specificationsVi: { "Chiều rộng": "70cm", "Chiều sâu": "75cm", "Chiều cao": "85cm", "Chất liệu": "Nhung + Kim loại" }
  },
  {
    slug: "floating-nightstand-pair",
    nameEn: "Pair of Floating Nightstands",
    nameVi: "Cặp Tủ Đầu Giường Treo Tường",
    descriptionEn: "Space-saving floating nightstands with drawer",
    descriptionVi: "Tủ đầu giường treo tường tiết kiệm không gian có ngăn kéo",
    price: 199.99,
    originalPrice: 299.99,
    images: ["/images/business-slide6.jpg", "/images/business-slide1.jpg"],
    room: "Bedroom",
    type: "Cabinet",
    category: "Storage",
    inStock: true,
    stock: 14,
    featured: false,
    featuresEn: ["Wall-mounted", "Set of 2", "Hidden drawer"],
    featuresVi: ["Gắn tường", "Bộ 2 cái", "Ngăn kéo ẩn"],
    longDescriptionEn: "Modern set of 2 floating nightstands that mount to the wall, each featuring a hidden drawer for storage while saving floor space.",
    longDescriptionVi: "Bộ 2 tủ đầu giường treo tường hiện đại gắn vào tường, mỗi cái có ngăn kéo ẩn để lưu trữ trong khi tiết kiệm không gian sàn.",
    specificationsEn: { "Width": "45cm each", "Depth": "30cm", "Height": "15cm", "Material": "MDF + Metal Hardware" },
    specificationsVi: { "Chiều rộng": "45cm mỗi cái", "Chiều sâu": "30cm", "Chiều cao": "15cm", "Chất liệu": "MDF + Kim loại" }
  }
];

async function addMoreProducts() {
  console.log("🛋️ Adding additional products for pagination testing...");
  
  try {
    for (const productData of additionalProducts) {
      const existingProduct = await prisma.product.findUnique({
        where: { slug: productData.slug }
      });
      
      if (!existingProduct) {
        await prisma.product.create({
          data: productData
        });
        console.log(`✅ Created product: ${productData.nameEn}`);
      } else {
        console.log(`⏭️ Product already exists: ${productData.nameEn}`);
      }
    }
    
    console.log(`\n🎉 Successfully added ${additionalProducts.length} additional products!`);
    
    // Show summary
    const totalProducts = await prisma.product.count();
    console.log(`📊 Total products in database: ${totalProducts}`);
    
  } catch (error) {
    console.error('❌ Error adding products:', error);
  } finally {
    await prisma.$disconnect();
  }
}

addMoreProducts();
